version: '3.8'

services:

  fe:
    image: node:20.12-buster
    command: ["sh", "-c", "npm install && npm run dev"]
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true

  be:
    image: gradle:8.10.2-jdk21
    command: ["sh", "-c", "DB_IP=172.17.0.1 gradle bootRun"]
    working_dir: /app
    volumes:
      - ./backend/:/app
    ports:
      - 8082:8080

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SomeKindOfSorta123GoodPassword!
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 5432:5432

  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - 8083:8080
